<?php
/**
 *  Created with PhpStorm
 * by User: @hseka
 * Date : 18/04/2020
 * Time: 22:48
 **/

namespace AppBundle\Security;

use AppBundle\Form\LoginForm;
use Doctrine\ORM\EntityManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Guard\Authenticator\AbstractFormLoginAuthenticator;
use Symfony\Component\Security\Guard\AbstractGuardAuthenticator;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Form\FormFactoryInterface;

class LoginformAuthenticator extends AbstractFormLoginAuthenticator
{
  /**
   * @var FormFactoryInterface
   */
  private $formFactory;
  private $em;
  private $router;

  public function __construct(FormFactoryInterface $formFactory, EntityManager $em, RouterInterface $router)
  {
    $this->formFactory = $formFactory;
    $this->em = $em;
    $this->router = $router;
  }

  public function getCredentials(Request $request)
  {
    // Méthode #1 :
    // $isLoginSubmit = $request->getPathInfo() == '/login' && $request->isMethod('POST');
    // ou Méthode #2 :
    // au lieu de coder en dur l'url '/login', on peut utiliser le nom de la route ('security_login') comme ci-dessous :
    // Si les deux conditions ci-dessous sont réunies, alors le User vient de soumettre le Formulaire de Login :
    $isLoginSubmit = $request->attributes->get('_route') === 'security_login' && $request->isMethod('POST');

    if(!$isLoginSubmit) {
      /* If you return null from getCredentials(),
        Symfony skips trying to authenticate the user
        and the request continues on, like normal. */
      return null;
    }

    /* A partir d'ici, on est bien dans la situation où
     * 1) L'url est "/login"
     * 2) La méthode de la requête est bien 'POST'
     *
     * ...Ainsi :
     * If the user is trying to login, our new task is to fetch the username & password and return them.
     */
    // 1) Création d'un formulaire de Login, et récupération des éléments :
    $form = $this->formFactory->create(LoginForm::class);
    $form->handleRequest($request);

    // 2) Ici, on récupère effectivement, depuis le formulaire LoginForm créé ci-dessus, le "username" et le "password" sous forme d'un tableau associatif => ['_username' => 'xxx', '_password' => 'xxx'] :
    $data = $form->getData();

    return $data;
  }

  // Récupération de l'objet User, s'il existe en base de donnée
  public function getUser($credentials, UserProviderInterface $userProvider)
  {
    $username = $credentials['_username'];

    return $this->em->getRepository('AppBundle:User')
              ->findOneBy(['email' => $username]);
  }

  // Vérification du mot de passe :
  public function checkCredentials($credentials, UserInterface $user)
  {
    $password = $credentials['_password'];

    if($password == 'iliketurtles') {
      return true;
    }
    return false;
  }


  // En cas d'échec de la vérification de mot de passe, l'utilisateur est redirigé vers la page de Login :
  protected function getLoginUrl()
  {
    return $this->router->generate('security_login');
  }
  // nouvelle méthode correspondant à "getLoginUrl()" :
  /*
  public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
  {
    return parent::onAuthenticationFailure($request, $exception); // TODO: Change the autogenerated stub
  }
  */


  // En cas de succès de l'authentification, l'utilisateur est redirigé vers la page indiquée ici :
  protected function getDefaultSuccessRedirectUrl()
  {
    return $this->router->generate('homepage');
  }
  /* nouvelle méthode correspondant à "getDefaultSuccessRedirectUrl()" :  :
  public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
  {
  }
  */
}