<?php

namespace AppBundle\Repository;

/**
 * ExcelDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExcelDataRepository extends \Doctrine\ORM\EntityRepository
{
}
